//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.PowerShell.Commands.Utility {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UtilityCommonStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UtilityCommonStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.PowerShell.Commands.Utility.UtilityCommonStrings", typeof(UtilityCommonStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command cannot be run because &apos;{0}&apos; is empty or blank. Please specify CSSUri and then run the command..
        /// </summary>
        public static string EmptyCSSUri {
            get {
                return ResourceManager.GetString("EmptyCSSUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command cannot be run because the file path &apos;{0}&apos; is not valid. Please provide a valid file path and then run the command..
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open the file because the current provider ({0}) cannot open files..
        /// </summary>
        public static string FileOpenError {
            get {
                return ResourceManager.GetString("FileOpenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; can not be read: {1}.
        /// </summary>
        public static string FileReadError {
            get {
                return ResourceManager.GetString("FileReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command cannot be run because AsHashTable parameter without AsString parameter works only for single property..
        /// </summary>
        public static string GroupObjectSingleProperty {
            get {
                return ResourceManager.GetString("GroupObjectSingleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command cannot be run because AsString parameter works together with AsHashtable parameter only..
        /// </summary>
        public static string GroupObjectWithHashTable {
            get {
                return ResourceManager.GetString("GroupObjectWithHashTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The objects grouped by this property cannot be expanded since there is a duplication of the key. Please give a valid property and try again..
        /// </summary>
        public static string InvalidOperation {
            get {
                return ResourceManager.GetString("InvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2} has one or more exceptions that are not valid..
        /// </summary>
        public static string Invalidpath {
            get {
                return ResourceManager.GetString("Invalidpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no matching result found for the given {2}..
        /// </summary>
        public static string NoMatchFound {
            get {
                return ResourceManager.GetString("NoMatchFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command is not supported on this operating system..
        /// </summary>
        public static string NotSupported {
            get {
                return ResourceManager.GetString("NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command cannot be run because the prefix value in the Namespace parameter is null. Provide a proper prefix and then run the command again..
        /// </summary>
        public static string SearchXMLPrefixNullError {
            get {
                return ResourceManager.GetString("SearchXMLPrefixNullError", resourceCulture);
            }
        }
    }
}
