//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.PowerShell.Commands.Utility {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VariableCommandStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VariableCommandStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.PowerShell.Commands.Utility.VariableCommandStrings", typeof(VariableCommandStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add variable.
        /// </summary>
        public static string AddVariableAction {
            get {
                return ResourceManager.GetString("AddVariableAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: {0}.
        /// </summary>
        public static string AddVariableTarget {
            get {
                return ResourceManager.GetString("AddVariableTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear variable.
        /// </summary>
        public static string ClearVariableAction {
            get {
                return ResourceManager.GetString("ClearVariableAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: {0}.
        /// </summary>
        public static string ClearVariableTarget {
            get {
                return ResourceManager.GetString("ClearVariableTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New variable.
        /// </summary>
        public static string NewVariableAction {
            get {
                return ResourceManager.GetString("NewVariableAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: {0} Value: {1}.
        /// </summary>
        public static string NewVariableTarget {
            get {
                return ResourceManager.GetString("NewVariableTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove variable.
        /// </summary>
        public static string RemoveVariableAction {
            get {
                return ResourceManager.GetString("RemoveVariableAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: {0}.
        /// </summary>
        public static string RemoveVariableTarget {
            get {
                return ResourceManager.GetString("RemoveVariableTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set variable.
        /// </summary>
        public static string SetVariableAction {
            get {
                return ResourceManager.GetString("SetVariableAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: {0} Value: {1}.
        /// </summary>
        public static string SetVariableTarget {
            get {
                return ResourceManager.GetString("SetVariableTarget", resourceCulture);
            }
        }
    }
}
