//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.PowerShell.Commands.Utility {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebCmdletStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebCmdletStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.PowerShell.Commands.Utility.WebCmdletStrings", typeof(WebCmdletStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the path &apos;{0}&apos; is denied..
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cmdlet cannot run because the following conflicting parameters are specified: Body and InFile. Specify either Body or Infile, then retry.  .
        /// </summary>
        public static string BodyConflict {
            get {
                return ResourceManager.GetString("BodyConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cmdlet cannot run because the following conflicting parameters are specified: Credential and UseDefaultCredentials. Specify either Credential or UseDefaultCredentials, then retry..
        /// </summary>
        public static string CredentialConflict {
            get {
                return ResourceManager.GetString("CredentialConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path &apos;{0}&apos; is resolved to a directory. Please specify the path to a file and retry..
        /// </summary>
        public static string DirecotryPathSpecified {
            get {
                return ResourceManager.GetString("DirecotryPathSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert the Json string because a dictionary converted from it contains duplicated keys &apos;{0}&apos; and &apos;{1}&apos;..
        /// </summary>
        public static string DuplicateKeysInJsonString {
            get {
                return ResourceManager.GetString("DuplicateKeysInJsonString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ConvertTo-Json and ConvertFrom-Json cmdlets require that the .NET extended profile be installed..
        /// </summary>
        public static string ExtendedProfileRequired {
            get {
                return ResourceManager.GetString("ExtendedProfileRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The response content cannot be parsed because the Internet Explorer engine is not available, or Internet Explorer&apos;s first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again. .
        /// </summary>
        public static string IEDomNotSupported {
            get {
                return ResourceManager.GetString("IEDomNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The converted JSON string is in bad format..
        /// </summary>
        public static string JsonStringInBadFormat {
            get {
                return ResourceManager.GetString("JsonStringInBadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum redirection count has been exceeded. To increase the number of redirections allowed, supply a higher value to the -MaximumRedirection parameter..
        /// </summary>
        public static string MaximumRedirectionCountExceeded {
            get {
                return ResourceManager.GetString("MaximumRedirectionCountExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path &apos;{0}&apos; can be resolved to multiple paths..
        /// </summary>
        public static string MultiplePathsResolved {
            get {
                return ResourceManager.GetString("MultiplePathsResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path &apos;{0}&apos; cannot be resolved to a file..
        /// </summary>
        public static string NoPathResolved {
            get {
                return ResourceManager.GetString("NoPathResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path &apos;{0}&apos; is not a file system path. Please specify the path to a file in the file system..
        /// </summary>
        public static string NotFilesystemPath {
            get {
                return ResourceManager.GetString("NotFilesystemPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cmdlet cannot run because the following parameter is missing: OutFile. Provide a valid OutFile parameter value when using the PassThru parameter, then retry..
        /// </summary>
        public static string OutFileMissing {
            get {
                return ResourceManager.GetString("OutFileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cmdlet cannot run because the following conflicting parameters are specified: ProxyCredential and ProxyUseDefaultCredentials. Specify either ProxyCredential or ProxyUseDefaultCredentials, then retry..
        /// </summary>
        public static string ProxyCredentialConflict {
            get {
                return ResourceManager.GetString("ProxyCredentialConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cmdlet cannot run because the following parameter is missing: Proxy. Provide a valid proxy URI for the Proxy parameter when using the ProxyCredential or UseDefaultProxyCredentials parameters, then retry..
        /// </summary>
        public static string ProxyUriNotSupplied {
            get {
                return ResourceManager.GetString("ProxyUriNotSupplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading web response completed. (Number of bytes read: {0}).
        /// </summary>
        public static string ReadResponseComplete {
            get {
                return ResourceManager.GetString("ReadResponseComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Web Response.
        /// </summary>
        public static string ReadResponseProgressActivity {
            get {
                return ResourceManager.GetString("ReadResponseProgressActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading response stream... (Number of bytes read: {0}).
        /// </summary>
        public static string ReadResponseProgressStatus {
            get {
                return ResourceManager.GetString("ReadResponseProgressStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation has timed out..
        /// </summary>
        public static string RequestTimeout {
            get {
                return ResourceManager.GetString("RequestTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cmdlet cannot run because the following conflicting parameters are specified: Session and SessionVariable. Specify either Session or SessionVariable, then retry..
        /// </summary>
        public static string SessionConflict {
            get {
                return ResourceManager.GetString("SessionConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve certificates because the thumbprint is not valid. Verify the thumbprint and retry. .
        /// </summary>
        public static string ThumbprintNotFound {
            get {
                return ResourceManager.GetString("ThumbprintNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing web request completed. (Number of bytes remaining: {0}).
        /// </summary>
        public static string WriteRequestComplete {
            get {
                return ResourceManager.GetString("WriteRequestComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing web request.
        /// </summary>
        public static string WriteRequestProgressActivity {
            get {
                return ResourceManager.GetString("WriteRequestProgressActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing request stream... (Number of bytes remaining: {0}).
        /// </summary>
        public static string WriteRequestProgressStatus {
            get {
                return ResourceManager.GetString("WriteRequestProgressStatus", resourceCulture);
            }
        }
    }
}
