//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.WindowsAzure.Management.SqlDatabase.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.WindowsAzure.Management.SqlDatabase.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}
        ///Error Code: {0}.
        /// </summary>
        internal static string DatabaseManagementErrorFormat {
            get {
                return ResourceManager.GetString("DatabaseManagementErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Request Id: &apos;{0}&apos;.
        /// </summary>
        internal static string ExceptionClientRequestId {
            get {
                return ResourceManager.GetString("ExceptionClientRequestId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Session Id: &apos;{0}&apos;.
        /// </summary>
        internal static string ExceptionClientSessionId {
            get {
                return ResourceManager.GetString("ExceptionClientSessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Id: &apos;{0}&apos;.
        /// </summary>
        internal static string ExceptionRequestId {
            get {
                return ResourceManager.GetString("ExceptionRequestId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The firewall rule &quot;{0}&quot; could not be found in the Windows Azure Sql Database server &quot;{1}&quot;..
        /// </summary>
        internal static string GetAzureSqlDatabaseServerFirewallRuleNotFound {
            get {
                return ResourceManager.GetString("GetAzureSqlDatabaseServerFirewallRuleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Windows Azure Sql Database server &quot;{0}&quot; could not be found in the currently selected subscription..
        /// </summary>
        internal static string GetAzureSqlDatabaseServerNotFound {
            get {
                return ResourceManager.GetString("GetAzureSqlDatabaseServerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a new Windows Azure Sql Database server..
        /// </summary>
        internal static string NewAzureSqlDatabaseServerDescription {
            get {
                return ResourceManager.GetString("NewAzureSqlDatabaseServerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding firewall rule &quot;{0}&quot; for Windows Azure Sql Database server &quot;{1}&quot;..
        /// </summary>
        internal static string NewAzureSqlDatabaseServerFirewallRuleDescription {
            get {
                return ResourceManager.GetString("NewAzureSqlDatabaseServerFirewallRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to add the firewall rule &quot;{0}&quot; for Windows Azure Sql Database server &quot;{1}&quot;?.
        /// </summary>
        internal static string NewAzureSqlDatabaseServerFirewallRuleWarning {
            get {
                return ResourceManager.GetString("NewAzureSqlDatabaseServerFirewallRuleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to create a new Windows Azure Sql Database server?.
        /// </summary>
        internal static string NewAzureSqlDatabaseServerWarning {
            get {
                return ResourceManager.GetString("NewAzureSqlDatabaseServerWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing Windows Azure Sql Database server &quot;{0}&quot;..
        /// </summary>
        internal static string RemoveAzureSqlDatabaseServerDescription {
            get {
                return ResourceManager.GetString("RemoveAzureSqlDatabaseServerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing firewall rule &quot;{0}&quot; for Windows Azure Sql Database server &quot;{1}&quot;..
        /// </summary>
        internal static string RemoveAzureSqlDatabaseServerFirewallRuleDescription {
            get {
                return ResourceManager.GetString("RemoveAzureSqlDatabaseServerFirewallRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the firewall rule &quot;{0}&quot; for Windows Azure Sql Database server &quot;{1}&quot;?.
        /// </summary>
        internal static string RemoveAzureSqlDatabaseServerFirewallRuleWarning {
            get {
                return ResourceManager.GetString("RemoveAzureSqlDatabaseServerFirewallRuleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the Windows Azure Sql Database server &quot;{0}&quot;?.
        /// </summary>
        internal static string RemoveAzureSqlDatabaseServerWarning {
            get {
                return ResourceManager.GetString("RemoveAzureSqlDatabaseServerWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetting administrator password for Windows Azure Sql Database server &quot;{0}&quot;..
        /// </summary>
        internal static string SetAzureSqlDatabaseServerAdminPasswordDescription {
            get {
                return ResourceManager.GetString("SetAzureSqlDatabaseServerAdminPasswordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset the administrator password for Windows Azure Sql Database server &quot;{0}&quot;?.
        /// </summary>
        internal static string SetAzureSqlDatabaseServerAdminPasswordWarning {
            get {
                return ResourceManager.GetString("SetAzureSqlDatabaseServerAdminPasswordWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating firewall rule &quot;{0}&quot; for Windows Azure Sql Database server &quot;{1}&quot;..
        /// </summary>
        internal static string SetAzureSqlDatabaseServerFirewallRuleDescription {
            get {
                return ResourceManager.GetString("SetAzureSqlDatabaseServerFirewallRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to update the firewall rule &quot;{0}&quot; for Windows Azure Sql Database server &quot;{1}&quot;?.
        /// </summary>
        internal static string SetAzureSqlDatabaseServerFirewallRuleWarning {
            get {
                return ResourceManager.GetString("SetAzureSqlDatabaseServerFirewallRuleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string ShouldProcessCaption {
            get {
                return ResourceManager.GetString("ShouldProcessCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not exist..
        /// </summary>
        internal static string UriDoesNotExist {
            get {
                return ResourceManager.GetString("UriDoesNotExist", resourceCulture);
            }
        }
    }
}
