namespace Microsoft.ActiveDirectory.Management
{
	internal enum ADAttributeSyntax
	{
		CaseExactString = 0,
		CaseIgnoreString = 1,
		NumericString = 2,
		DirectoryString = 3,
		OctetString = 4,
		SecurityDescriptor = 5,
		Int = 6,
		Int64 = 7,
		Bool = 8,
		Oid = 9,
		GeneralizedTime = 10,
		UtcTime = 11,
		DN = 12,
		DNWithBinary = 13,
		DNWithString = 14,
		Enumeration = 15,
		IA5String = 16,
		PrintableString = 17,
		Sid = 18,
		AccessPointDN = 19,
		ORName = 20,
		PresentationAddress = 21,
		CertificatePair = 22,
		CountryString = 23,
		DataQualitySyntax = 24,
		DeliveryMethod = 25,
		DSAQualitySyntax = 26,
		EnhancedGuidE = 27,
		FacsimileTelephoneNumer = 28,
		Fax = 29,
		GuidE = 30,
		Jpeg = 40,
		AttributeTypeDescription = 41,
		MailPreference = 42,
		ORAddress = 43,
		NameAndOptionalUid = 44,
		ObjectClassDescription = 45,
		OtherMailBox = 46,
		Audio = 47,
		PostalAddress = 48,
		TelephoneNumber = 49,
		TeletexTerminalIdentifier = 50,
		TelexNumber = 51,
		BitString = 52,
		Certificate = 53,
		CertificateList = 54,
		ReplicaLink = 55,
		NotFound = 56,
		Password = 57
	}
}