//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.PowerShell.Security {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UtilsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UtilsStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.PowerShell.Security.UtilsStrings", typeof(UtilsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot digitally sign file because file {0} is smaller than 4 bytes in size. Files must be at least 4 bytes in order to be digitally signed..
        /// </summary>
        public static string FileSmallerThan4Bytes {
            get {
                return ResourceManager.GetString("FileSmallerThan4Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create an empty SACL..
        /// </summary>
        public static string GetEmptySaclFail {
            get {
                return ResourceManager.GetString("GetEmptySaclFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get the ACL because the necessary method, GetSecurityDescriptor, does not exist..
        /// </summary>
        public static string GetMethodNotFound {
            get {
                return ResourceManager.GetString("GetMethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create a SACL with the specified central access policy..
        /// </summary>
        public static string GetSaclWithCapIdFail {
            get {
                return ResourceManager.GetString("GetSaclWithCapIdFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not enable SeSecurityPrivilege..
        /// </summary>
        public static string GetTokenWithEnabledPrivilegeFail {
            get {
                return ResourceManager.GetString("GetTokenWithEnabledPrivilegeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central Access Policy identifier or name is not valid. If specifying an identifier, it must begin with S-1-17. If specifying a name, the policy must be applied on the target machine..
        /// </summary>
        public static string InvalidCentralAccessPolicyIdentifier {
            get {
                return ResourceManager.GetString("InvalidCentralAccessPolicyIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClearCentralAccessPolicy and CentralAccessPolicy parameters cannot be used at the same time..
        /// </summary>
        public static string InvalidCentralAccessPolicyParameters {
            get {
                return ResourceManager.GetString("InvalidCentralAccessPolicyParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not perform operation because an exception was thrown during method invoke..
        /// </summary>
        public static string MethodInvokeFail {
            get {
                return ResourceManager.GetString("MethodInvokeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot perform the operation because it is not supported on the object found in path {0}..
        /// </summary>
        public static string OperationNotSupportedOnPath {
            get {
                return ResourceManager.GetString("OperationNotSupportedOnPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows PowerShell credential request..
        /// </summary>
        public static string PromptForCredential_DefaultCaption {
            get {
                return ResourceManager.GetString("PromptForCredential_DefaultCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not set central access policy..
        /// </summary>
        public static string SetCentralAccessPolicyFail {
            get {
                return ResourceManager.GetString("SetCentralAccessPolicyFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set the ACL because the method that it needs to invoke, SetSecurityDescriptor, does not exist..
        /// </summary>
        public static string SetMethodNotFound {
            get {
                return ResourceManager.GetString("SetMethodNotFound", resourceCulture);
            }
        }
    }
}
