namespace Microsoft.Data.Edm
{
	internal enum EdmPrimitiveTypeKind
	{
		None,
		Binary,
		Boolean,
		Byte,
		DateTime,
		DateTimeOffset,
		Decimal,
		Double,
		Guid,
		Int16,
		Int32,
		Int64,
		SByte,
		Single,
		String,
		Stream,
		Time,
		Geography,
		GeographyPoint,
		GeographyLineString,
		GeographyPolygon,
		GeographyCollection,
		GeographyMultiPolygon,
		GeographyMultiLineString,
		GeographyMultiPoint,
		Geometry,
		GeometryPoint,
		GeometryLineString,
		GeometryPolygon,
		GeometryCollection,
		GeometryMultiPolygon,
		GeometryMultiLineString,
		GeometryMultiPoint
	}
}