//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Management.Automation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Authenticode {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Authenticode() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Management.Automation.Authenticode", typeof(Authenticode).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to run software from this untrusted publisher?.
        /// </summary>
        public static string AuthenticodePromptCaption {
            get {
                return ResourceManager.GetString("AuthenticodePromptCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} is published by {1} and is not trusted on your system. Only run scripts from trusted publishers..
        /// </summary>
        public static string AuthenticodePromptText {
            get {
                return ResourceManager.GetString("AuthenticodePromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software {0} is published by an unknown publisher. It is recommended that you do not run this software..
        /// </summary>
        public static string AuthenticodePromptText_UnknownPublisher {
            get {
                return ResourceManager.GetString("AuthenticodePromptText_UnknownPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot sign code. The specified certificate is not suitable for code signing..
        /// </summary>
        public static string CertNotGoodForSigning {
            get {
                return ResourceManager.GetString("CertNotGoodForSigning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Always run.
        /// </summary>
        public static string Choice_AlwaysRun {
            get {
                return ResourceManager.GetString("Choice_AlwaysRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run the script from this publisher now, and do not prompt me to run this script in the future..
        /// </summary>
        public static string Choice_AlwaysRun_Help {
            get {
                return ResourceManager.GetString("Choice_AlwaysRun_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Do not run.
        /// </summary>
        public static string Choice_DoNotRun {
            get {
                return ResourceManager.GetString("Choice_DoNotRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not run the script from this publisher now, and continue to prompt me to run this script in the future..
        /// </summary>
        public static string Choice_DoNotRun_Help {
            get {
                return ResourceManager.GetString("Choice_DoNotRun_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne&amp;ver run.
        /// </summary>
        public static string Choice_NeverRun {
            get {
                return ResourceManager.GetString("Choice_NeverRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not run the script from this publisher now, and do not prompt me to run this script in future. Future attempts to run this script will result in a silent failure..
        /// </summary>
        public static string Choice_NeverRun_Help {
            get {
                return ResourceManager.GetString("Choice_NeverRun_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Run once.
        /// </summary>
        public static string Choice_RunOnce {
            get {
                return ResourceManager.GetString("Choice_RunOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run the script from this publisher now, and continue to prompt me to run this script in the future..
        /// </summary>
        public static string Choice_RunOnce_Help {
            get {
                return ResourceManager.GetString("Choice_RunOnce_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Suspend.
        /// </summary>
        public static string Choice_Suspend {
            get {
                return ResourceManager.GetString("Choice_Suspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause the current pipeline and return to the command prompt. Type exit to resume operation when you are done..
        /// </summary>
        public static string Choice_Suspend_Help {
            get {
                return ResourceManager.GetString("Choice_Suspend_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot sign code. The hash algorithm is not supported..
        /// </summary>
        public static string InvalidHashAlgorithm {
            get {
                return ResourceManager.GetString("InvalidHashAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} cannot be loaded because its operation is blocked by software restriction policies. For more information, contact your system administrator..
        /// </summary>
        public static string Reason_DisallowedBySafer {
            get {
                return ResourceManager.GetString("Reason_DisallowedBySafer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} cannot be loaded because you have elected to not run this software now..
        /// </summary>
        public static string Reason_DoNotRun {
            get {
                return ResourceManager.GetString("Reason_DoNotRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} cannot be loaded because its content could not be read..
        /// </summary>
        public static string Reason_FileContentUnavailable {
            get {
                return ResourceManager.GetString("Reason_FileContentUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} cannot be loaded because you have elected to never run software from this publisher..
        /// </summary>
        public static string Reason_NeverRun {
            get {
                return ResourceManager.GetString("Reason_NeverRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} is published by {1}. This publisher is explicitly untrusted on your system. The script will not run on the system. Please see &quot;get-help about_signing&quot; for more details..
        /// </summary>
        public static string Reason_NotTrusted {
            get {
                return ResourceManager.GetString("Reason_NotTrusted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at http://go.microsoft.com/fwlink/?LinkID=135170..
        /// </summary>
        public static string Reason_RestrictedMode {
            get {
                return ResourceManager.GetString("Reason_RestrictedMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} cannot be loaded. {1}..
        /// </summary>
        public static string Reason_Unknown {
            get {
                return ResourceManager.GetString("Reason_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security warning.
        /// </summary>
        public static string RemoteFilePromptCaption {
            get {
                return ResourceManager.GetString("RemoteFilePromptCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run only scripts that you trust. While scripts from the internet can be useful, this script can potentially harm your computer. Do you want to run {0}?.
        /// </summary>
        public static string RemoteFilePromptText {
            get {
                return ResourceManager.GetString("RemoteFilePromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot sign code. The TimeStamp server URL must be fully qualified in the form of http://&lt;server url&gt;.
        /// </summary>
        public static string TimeStampUrlRequired {
            get {
                return ResourceManager.GetString("TimeStampUrlRequired", resourceCulture);
            }
        }
    }
}
