//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Management.Automation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConsoleInfoErrorStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConsoleInfoErrorStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Management.Automation.ConsoleInfoErrorStrings", typeof(ConsoleInfoErrorStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Windows PowerShell version {0}. Windows PowerShell version {1} is supported in the current console..
        /// </summary>
        public static string AddPSSnapInBadMonadVersion {
            get {
                return ResourceManager.GetString("AddPSSnapInBadMonadVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad console file extension. Console file extension must be psc1..
        /// </summary>
        public static string BadConsoleExtension {
            get {
                return ResourceManager.GetString("BadConsoleExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required element &quot;ConsoleSchemaVersion&quot; in {0} is missing or incorrect..
        /// </summary>
        public static string BadConsoleVersion {
            get {
                return ResourceManager.GetString("BadConsoleVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Windows PowerShell version {0}. Windows PowerShell version {1} is supported on this computer..
        /// </summary>
        public static string BadMonadVersion {
            get {
                return ResourceManager.GetString("BadMonadVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown element {0} found. &quot;{1}&quot; should have &quot;{2}&quot; and &quot;{3}&quot; elements only..
        /// </summary>
        public static string BadXMLElementFound {
            get {
                return ResourceManager.GetString("BadXMLElementFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Console file. Multiple entries found for element PSConsoleFile. Only one entry supported for this version..
        /// </summary>
        public static string BadXMLFormat {
            get {
                return ResourceManager.GetString("BadXMLFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a system Windows PowerShell Snap-In that is loaded by Windows PowerShell..
        /// </summary>
        public static string CannotLoadDefault {
            get {
                return ResourceManager.GetString("CannotLoadDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when loading the system Windows PowerShell Snap-Ins. Please contact Microsoft Support Services..
        /// </summary>
        public static string CannotLoadDefaults {
            get {
                return ResourceManager.GetString("CannotLoadDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove the Windows PowerShell Snap-In {0} because it is a system snap-in. Verify the name of the snap-in being removed and try again..
        /// </summary>
        public static string CannotRemoveDefault {
            get {
                return ResourceManager.GetString("CannotRemoveDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove the Windows PowerShell Snap-In {0} because it is not loaded. Verify the name of the snap-in being removed and try again..
        /// </summary>
        public static string CannotRemovePSSnapIn {
            get {
                return ResourceManager.GetString("CannotRemovePSSnapIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cmdlet is not supported by the custom shell..
        /// </summary>
        public static string CmdletNotAvailable {
            get {
                return ResourceManager.GetString("CmdletNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save the file because the file name format is not valid. Specify a file name using the command: export-console -path..
        /// </summary>
        public static string ConsoleCannotbeConvertedToString {
            get {
                return ResourceManager.GetString("ConsoleCannotbeConvertedToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot export to a console because no console is loaded or no name is specified..
        /// </summary>
        public static string ConsoleFileNameNotResolved {
            get {
                return ResourceManager.GetString("ConsoleFileNameNotResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot export to this file because file {0} is read-only. Change the read-only attribute of the file to read-write, or export to a different file..
        /// </summary>
        public static string ConsoleFileReadOnly {
            get {
                return ResourceManager.GetString("ConsoleFileReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save the console file because wildcard characters were used. Specify a console file without wildcard characters..
        /// </summary>
        public static string ConsoleFileWildCardsNotSupported {
            get {
                return ResourceManager.GetString("ConsoleFileWildCardsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following errors occurred when loading console {0}: {1}.
        /// </summary>
        public static string ConsoleLoadFailure {
            get {
                return ResourceManager.GetString("ConsoleLoadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set the ConsoleFileName variable to {0}. File {0} was saved..
        /// </summary>
        public static string ConsoleVariableCannotBeSet {
            get {
                return ResourceManager.GetString("ConsoleVariableCannotBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save operation failed. Cannot remove file {0}..
        /// </summary>
        public static string ExportConsoleCannotDeleteFile {
            get {
                return ResourceManager.GetString("ExportConsoleCannotDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} already exists and {1} was specified..
        /// </summary>
        public static string FileExistsNoClobber {
            get {
                return ResourceManager.GetString("FileExistsNoClobber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cmdlet {0}.
        /// </summary>
        public static string FileNameCaptionForExportConsole {
            get {
                return ResourceManager.GetString("FileNameCaptionForExportConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save file. Save operation cancelled..
        /// </summary>
        public static string FileNameNotResolved {
            get {
                return ResourceManager.GetString("FileNameNotResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply values for the following parameters:.
        /// </summary>
        public static string FileNamePromptMessage {
            get {
                return ResourceManager.GetString("FileNamePromptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The console file is not valid because the Windows PowerShell Snap-In name is missing..
        /// </summary>
        public static string IDNotFound {
            get {
                return ResourceManager.GetString("IDNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required element &quot;PSConsoleFile&quot; in {0} is missing or incorrect..
        /// </summary>
        public static string MonadConsoleNotFound {
            get {
                return ResourceManager.GetString("MonadConsoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required element &quot;PSVersion&quot; in {0} is missing or incorrect..
        /// </summary>
        public static string MonadVersionNotFound {
            get {
                return ResourceManager.GetString("MonadVersionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console file not valid. Only one instance of element &quot;{0}&quot; is allowed..
        /// </summary>
        public static string MultipleMshSnapinsElementNotSupported {
            get {
                return ResourceManager.GetString("MultipleMshSnapinsElementNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path {0} is not an absolute path..
        /// </summary>
        public static string PathNotAbsolute {
            get {
                return ResourceManager.GetString("PathNotAbsolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot export a console file because no console file has been specified. Do you want to continue with export?.
        /// </summary>
        public static string PromptForExportConsole {
            get {
                return ResourceManager.GetString("PromptForExportConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can only save a file when you are in a file provider. Current provider is not a file provider..
        /// </summary>
        public static string ProviderNotSupported {
            get {
                return ResourceManager.GetString("ProviderNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add Windows PowerShell Snap-In {0} because it is already added. Verify the name of the snap-in and try again..
        /// </summary>
        public static string PSSnapInAlreadyExists {
            get {
                return ResourceManager.GetString("PSSnapInAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Windows PowerShell Snap-In module {0} does not have required Windows PowerShell Snap-In strong name {1}..
        /// </summary>
        public static string PSSnapInAssemblyNameMismatch {
            get {
                return ResourceManager.GetString("PSSnapInAssemblyNameMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any Windows PowerShell Snap-In information for {0}..
        /// </summary>
        public static string PSSnapInDoesNotExist {
            get {
                return ResourceManager.GetString("PSSnapInDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cmdlet &apos;{0}&apos; is present more than once in Windows PowerShell Snap- In &apos;{1}&apos;..
        /// </summary>
        public static string PSSnapInDuplicateCmdlets {
            get {
                return ResourceManager.GetString("PSSnapInDuplicateCmdlets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows PowerShell provider &apos;{0}&apos; is present more than once in Windows PowerShell Snap-In &apos;{1}&apos;..
        /// </summary>
        public static string PSSnapInDuplicateProviders {
            get {
                return ResourceManager.GetString("PSSnapInDuplicateProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load Windows PowerShell Snap-In {0} because of the following error: {1}.
        /// </summary>
        public static string PSSnapInLoadFailure {
            get {
                return ResourceManager.GetString("PSSnapInLoadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows PowerShell Snap-In &quot;{0}&quot; is loaded with the following warnings: {1}.
        /// </summary>
        public static string PSSnapInLoadWarning {
            get {
                return ResourceManager.GetString("PSSnapInLoadWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad console file.  Element {0} is not valid..
        /// </summary>
        public static string PSSnapInNotFound {
            get {
                return ResourceManager.GetString("PSSnapInNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load the Windows PowerShell Snap-In because an error occurred while reading the registry information for the snap-in..
        /// </summary>
        public static string PSSnapInReadError {
            get {
                return ResourceManager.GetString("PSSnapInReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to save a console file with no name. Use export-console with the Path parameter to save the console file..
        /// </summary>
        public static string SaveDefaultError {
            get {
                return ResourceManager.GetString("SaveDefaultError", resourceCulture);
            }
        }
    }
}
