//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Management.Automation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HelpErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HelpErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Management.Automation.HelpErrors", typeof(HelpErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launching a program to show online help failed. No program is associated to launch URI {0}..
        /// </summary>
        public static string CannotLaunchURI {
            get {
                return ResourceManager.GetString("CannotLaunchURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForwardHelpTargetName cannot refer to the function itself..
        /// </summary>
        public static string CircularDependencyInHelpForwarding {
            get {
                return ResourceManager.GetString("CircularDependencyInHelpForwarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use the {0}, install the Windows PowerShell ISE feature from Server Manager and restart this application. ({1}).
        /// </summary>
        public static string GraphicalHostAssemblyIsNotFound {
            get {
                return ResourceManager.GetString("GraphicalHostAssemblyIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot process Help category because &quot;{0}&quot; is not a valid Help category..
        /// </summary>
        public static string HelpCategoryInvalid {
            get {
                return ResourceManager.GetString("HelpCategoryInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load Help file &quot;{0}&quot;. Details: {1}..
        /// </summary>
        public static string HelpFileLoadFailure {
            get {
                return ResourceManager.GetString("HelpFileLoadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access Help file &quot;{0}&quot; because the current user is not authorized to access the file. Details: {1}..
        /// </summary>
        public static string HelpFileNotAccessible {
            get {
                return ResourceManager.GetString("HelpFileNotAccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help file &quot;{0}&quot; is not a valid xml document. Details: {1}..
        /// </summary>
        public static string HelpFileNotValid {
            get {
                return ResourceManager.GetString("HelpFileNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load Help file. The following {1} error(s) happened while loading help file &quot;{0}&quot;..
        /// </summary>
        public static string HelpLoadError {
            get {
                return ResourceManager.GetString("HelpLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get-Help could not find {0} in a help file in this session. To download updated help topics type: &quot;Update-Help&quot;. To get help online, search for the help topic in the TechNet library at http://go.microsoft.com/fwlink/?LinkID=107116..
        /// </summary>
        public static string HelpNotFound {
            get {
                return ResourceManager.GetString("HelpNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified Uri {0} is not valid..
        /// </summary>
        public static string InvalidURI {
            get {
                return ResourceManager.GetString("InvalidURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading help content for {0} from file {1}. Details: {2}. To download updated help topics type: &quot;Update-Help&quot;. To get help online, search for the help topic in the TechNet library at http://go.microsoft.com/fwlink/?LinkID=107116..
        /// </summary>
        public static string LoadHelpFileForTargetFailed {
            get {
                return ResourceManager.GetString("LoadHelpFileForTargetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node &quot;{0}&quot; can have at maximum {2} child node(s) of type &quot;{1}&quot;. Node Path: {3}..
        /// </summary>
        public static string MamlInvalidChildNodeCountError {
            get {
                return ResourceManager.GetString("MamlInvalidChildNodeCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node &quot;{0}&quot; cannot have &quot;{1}&quot; as a child node. Node Path: {2}..
        /// </summary>
        public static string MamlInvalidChildNodeError {
            get {
                return ResourceManager.GetString("MamlInvalidChildNodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple help topics are found, use only one help topic with -{0} option..
        /// </summary>
        public static string MultipleOnlineTopicsNotSupported {
            get {
                return ResourceManager.GetString("MultipleOnlineTopicsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No parameter matches criteria {0}..
        /// </summary>
        public static string NoParmsFound {
            get {
                return ResourceManager.GetString("NoParmsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The online version of this Help topic cannot be displayed because the Internet address (URI) of the Help topic is not specified in the command code or in the help file for the command..
        /// </summary>
        public static string NoURIFound {
            get {
                return ResourceManager.GetString("NoURIFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not supported by the requested help category..
        /// </summary>
        public static string ParamNotSupported {
            get {
                return ResourceManager.GetString("ParamNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The protocol specified in the Uri &quot;{0}&quot; is not supported. Only &quot;{1}&quot; and &quot;{2}&quot; protocols are supported..
        /// </summary>
        public static string ProtocolNotSupported {
            get {
                return ResourceManager.GetString("ProtocolNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider &quot;{0}&quot; cannot be loaded. Details: {1}..
        /// </summary>
        public static string ProviderLoadError {
            get {
                return ResourceManager.GetString("ProviderLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the registry key: &quot;{0}{1}&quot;, using &quot;{2}&quot; to load the help files..
        /// </summary>
        public static string RegistryPathNotFound {
            get {
                return ResourceManager.GetString("RegistryPathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get help from remote runspace, because the runspace is not opened.  Open the runspace by running one of implicit remoting commands and then try getting the help again..
        /// </summary>
        public static string RemoteRunspaceNotAvailable {
            get {
                return ResourceManager.GetString("RemoteRunspaceNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not work in a remote session..
        /// </summary>
        public static string RemotingNotSupportedForFeature {
            get {
                return ResourceManager.GetString("RemotingNotSupportedForFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command did not update help topics for the Windows PowerShell core commands or for any modules in the $pshome\Modules directory. To update these help topics, start Windows PowerShell with the &quot;Run as Administrator&quot; option and try the command again..
        /// </summary>
        public static string UpdatableHelpRequiresElevation {
            get {
                return ResourceManager.GetString("UpdatableHelpRequiresElevation", resourceCulture);
            }
        }
    }
}
