//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Management.Automation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RunspacePoolStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RunspacePoolStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Management.Automation.RunspacePoolStrings", typeof(RunspacePoolStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This {0} object was not created by calling {1} on this RunspacePool instance..
        /// </summary>
        public static string AsyncResultNotOwned {
            get {
                return ResourceManager.GetString("AsyncResultNotOwned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This runspace pool cannot be connected because the corresponding server side runspace pool is connected to another client..
        /// </summary>
        public static string CannotConnect {
            get {
                return ResourceManager.GetString("CannotConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open the runspace pool because it is not in the &apos;BeforeOpen&apos; state. The current state is &apos;{0}&apos;..
        /// </summary>
        public static string CannotOpenAgain {
            get {
                return ResourceManager.GetString("CannotOpenAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This runspace pool {0} is not configured to provide disconnected Windows PowerShell objects for commands running on the remote server.  Use the RunspacePool class GetRunspacePools() static method to query the server and return runspace pool objects that are configured to do this..
        /// </summary>
        public static string CannotReconstructCommands {
            get {
                return ResourceManager.GetString("CannotReconstructCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set the TypeTable data unless runspace pool is in the Disconnected or BeforeOpen state.  Current state is {0}..
        /// </summary>
        public static string CannotSetTypeTable {
            get {
                return ResourceManager.GetString("CannotSetTypeTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot perform operation because the runspace pool is in the Disconnected state..
        /// </summary>
        public static string CannotWhileDisconnected {
            get {
                return ResourceManager.GetString("CannotWhileDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property cannot be changed after the runspace pool has been opened..
        /// </summary>
        public static string ChangePropertyAfterOpen {
            get {
                return ResourceManager.GetString("ChangePropertyAfterOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The disconnect operation is not supported on the server.  The server must be running Windows PowerShell version 3 or greater for remote runspace pool disconnect support..
        /// </summary>
        public static string DisconnectNotSupportedOnServer {
            get {
                return ResourceManager.GetString("DisconnectNotSupportedOnServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot perform operation because the runspace pool is not in the &apos;{0}&apos; state. The current state is &apos;{1}&apos;..
        /// </summary>
        public static string InvalidRunspacePoolState {
            get {
                return ResourceManager.GetString("InvalidRunspacePoolState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The state of the runspace pool is not valid for this operation..
        /// </summary>
        public static string InvalidRunspacePoolStateGeneral {
            get {
                return ResourceManager.GetString("InvalidRunspacePoolStateGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum pool size cannot be less than 1..
        /// </summary>
        public static string MaxPoolLessThan1 {
            get {
                return ResourceManager.GetString("MaxPoolLessThan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum pool size cannot be greater than the maximum pool size..
        /// </summary>
        public static string MinPoolGreaterThanMaxPool {
            get {
                return ResourceManager.GetString("MinPoolGreaterThanMaxPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum pool size cannot be less than 1..
        /// </summary>
        public static string MinPoolLessThan1 {
            get {
                return ResourceManager.GetString("MinPoolLessThan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This runspace does not support disconnect and connect operations..
        /// </summary>
        public static string RunspaceDisconnectConnectNotSupported {
            get {
                return ResourceManager.GetString("RunspaceDisconnectConnectNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot release the runspace to this pool as the runspace does not belong to this pool..
        /// </summary>
        public static string RunspaceNotBelongsToPool {
            get {
                return ResourceManager.GetString("RunspaceNotBelongsToPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The runspace pool is closed..
        /// </summary>
        public static string RunspacePoolClosed {
            get {
                return ResourceManager.GetString("RunspacePoolClosed", resourceCulture);
            }
        }
    }
}
