//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Management.Automation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RunspaceStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RunspaceStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Management.Automation.RunspaceStrings", typeof(RunspaceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A SessionStateProxy method call is in progress. Concurrent SessionStateProxy method calls are not allowed..
        /// </summary>
        public static string AnotherSessionStateProxyInProgress {
            get {
                return ResourceManager.GetString("AnotherSessionStateProxyInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect PSSession because it is not in Disconnected state or is not available for connection..
        /// </summary>
        public static string CannotConnect {
            get {
                return ResourceManager.GetString("CannotConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open runspace because runspace is not in the BeforeOpen state. Current state of runspace is &apos;{0}&apos;..
        /// </summary>
        public static string CannotOpenAgain {
            get {
                return ResourceManager.GetString("CannotOpenAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property cannot be changed after the runspace has been opened..
        /// </summary>
        public static string ChangePropertyAfterOpen {
            get {
                return ResourceManager.GetString("ChangePropertyAfterOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more errors occurred during processing the module &apos;{0}&apos; specified in the InitialSessionState object used to create this runspace. See the ErrorRecords property for a complete list of errors..
        /// </summary>
        public static string CmdletNotFoundWhileLoadingModulesOnRunspaceOpen {
            get {
                return ResourceManager.GetString("CmdletNotFoundWhileLoadingModulesOnRunspaceOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipeline not run because a pipeline is already running. Pipelines cannot be run concurrently..
        /// </summary>
        public static string ConcurrentInvokeNotAllowed {
            get {
                return ResourceManager.GetString("ConcurrentInvokeNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Connect operation is not supported on local runspaces..
        /// </summary>
        public static string ConnectNotSupported {
            get {
                return ResourceManager.GetString("ConnectNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug stream redirection is not supported on the targeted remote computer..
        /// </summary>
        public static string DebugRedirectionNotSupported {
            get {
                return ResourceManager.GetString("DebugRedirectionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect and Connect operations are not supported on local run spaces..
        /// </summary>
        public static string DisconnectConnectNotSupported {
            get {
                return ResourceManager.GetString("DisconnectConnectNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A non-remoted runspace cannot be disconnected..
        /// </summary>
        public static string DisconnectNotSupported {
            get {
                return ResourceManager.GetString("DisconnectNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The disconnection operation is not supported on the remote computer. To support disconnecting, the remote computer must be running Windows PowerShell 3.0 or a later version of Windows PowerShell..
        /// </summary>
        public static string DisconnectNotSupportedOnServer {
            get {
                return ResourceManager.GetString("DisconnectNotSupportedOnServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more errors occurred processing the module &apos;{0}&apos; specified in the InitialSessionState object used to create this runspace. See the ErrorRecords property for a complete list of errors. The first error was: {1}.
        /// </summary>
        public static string ErrorLoadingModulesOnRunspaceOpen {
            get {
                return ResourceManager.GetString("ErrorLoadingModulesOnRunspaceOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value for parameter cannot be PipelineResultTypes.None or PipelineResultTypes.Output..
        /// </summary>
        public static string InvalidMyResultError {
            get {
                return ResourceManager.GetString("InvalidMyResultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State of pipeline is not valid for this operation..
        /// </summary>
        public static string InvalidPipelineStateStateGeneral {
            get {
                return ResourceManager.GetString("InvalidPipelineStateStateGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot construct RemoteRunspace. Passed in RunspacePool object is not valid..
        /// </summary>
        public static string InvalidRunspacePool {
            get {
                return ResourceManager.GetString("InvalidRunspacePool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State of runspace is not valid for this operation..
        /// </summary>
        public static string InvalidRunspaceStateGeneral {
            get {
                return ResourceManager.GetString("InvalidRunspaceStateGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The thread options can only be changed if the apartment state is MTA, the current options are UseNewThread or UseCurrentThread and the new value is ReuseThread..
        /// </summary>
        public static string InvalidThreadOptionsChange {
            get {
                return ResourceManager.GetString("InvalidThreadOptionsChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid values for parameter are PipelineResultTypes.Output or PipelineResultTypes.Null.
        /// </summary>
        public static string InvalidValueToResult {
            get {
                return ResourceManager.GetString("InvalidValueToResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid value for parameter is PipelineResultTypes.Output..
        /// </summary>
        public static string InvalidValueToResultError {
            get {
                return ResourceManager.GetString("InvalidValueToResultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nested pipeline cannot be invoked asynchronously. Use Invoke method..
        /// </summary>
        public static string NestedPipelineInvokeAsync {
            get {
                return ResourceManager.GetString("NestedPipelineInvokeAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nested pipeline should run only from a running pipeline..
        /// </summary>
        public static string NestedPipelineNoParentPipeline {
            get {
                return ResourceManager.GetString("NestedPipelineNoParentPipeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipeline does not contain any command..
        /// </summary>
        public static string NoCommandInPipeline {
            get {
                return ResourceManager.GetString("NoCommandInPipeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no disconnected command associated with this runspace..
        /// </summary>
        public static string NoDisconnectedCommand {
            get {
                return ResourceManager.GetString("NoDisconnectedCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipeline cannot be invoked while a SessionStateProxy method call is in progress..
        /// </summary>
        public static string NoPipelineWhenSessionStateProxyInProgress {
            get {
                return ResourceManager.GetString("NoPipelineWhenSessionStateProxyInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A pipeline is already running. Concurrent SessionStateProxy method call is not allowed..
        /// </summary>
        public static string NoSessionStateProxyWhenPipelineInProgress {
            get {
                return ResourceManager.GetString("NoSessionStateProxyWhenPipelineInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command cannot be completed. Script invocation is not supported on this session configuration. This might be because it is in no-language mode..
        /// </summary>
        public static string NotSupportedOnRestrictedRunspace {
            get {
                return ResourceManager.GetString("NotSupportedOnRestrictedRunspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter name or value must be specified..
        /// </summary>
        public static string ParameterNameOrValueNeeded {
            get {
                return ResourceManager.GetString("ParameterNameOrValueNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot invoke pipeline because it has been invoked earlier..
        /// </summary>
        public static string PipelineReInvokeNotAllowed {
            get {
                return ResourceManager.GetString("PipelineReInvokeNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runspace cannot be closed while a SessionStateProxy method call is in progress..
        /// </summary>
        public static string RunspaceCloseInvalidWhileSessionStateProxy {
            get {
                return ResourceManager.GetString("RunspaceCloseInvalidWhileSessionStateProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot perform operation because runspace is not in the Opened state. Current state of runspace is &apos;{0}&apos;..
        /// </summary>
        public static string RunspaceNotInOpenedState {
            get {
                return ResourceManager.GetString("RunspaceNotInOpenedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot invoke pipeline because runspace is not in the Opened state. Current state of runspace is &apos;{0}&apos;..
        /// </summary>
        public static string RunspaceNotOpenForPipeline {
            get {
                return ResourceManager.GetString("RunspaceNotOpenForPipeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect pipeline because runspace is not in the Opened state.  Current state of runspace is &apos;{0}&apos;..
        /// </summary>
        public static string RunspaceNotOpenForPipelineConnect {
            get {
                return ResourceManager.GetString("RunspaceNotOpenForPipelineConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session is busy. You will be connected to the session as soon as it is available. To cancel the Enter-PSSession command, press Ctrl-C..
        /// </summary>
        public static string RunspaceNotReady {
            get {
                return ResourceManager.GetString("RunspaceNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be false when language mode is {1} or {2}..
        /// </summary>
        public static string UseLocalScopeNotAllowed {
            get {
                return ResourceManager.GetString("UseLocalScopeNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbose stream redirection is not supported on the targeted remote computer..
        /// </summary>
        public static string VerboseRedirectionNotSupported {
            get {
                return ResourceManager.GetString("VerboseRedirectionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning stream redirection is not supported on the targeted remote computer..
        /// </summary>
        public static string WarningRedirectionNotSupported {
            get {
                return ResourceManager.GetString("WarningRedirectionNotSupported", resourceCulture);
            }
        }
    }
}
