namespace System.Management.Automation.Remoting
{
    using System;

    internal enum RemoteHostMethodId
    {
        EnterNestedPrompt = 7,
        ExitNestedPrompt = 8,
        FlushInputBuffer = 0x2f,
        GetBackgroundColor = 0x1d,
        GetBufferContents = 50,
        GetBufferSize = 0x25,
        GetCurrentCulture = 4,
        GetCurrentUICulture = 5,
        GetCursorPosition = 0x1f,
        GetCursorSize = 0x23,
        GetForegroundColor = 0x1b,
        GetInstanceId = 3,
        GetIsRunspacePushed = 0x36,
        GetKeyAvailable = 0x2d,
        GetMaxPhysicalWindowSize = 0x2c,
        GetMaxWindowSize = 0x2b,
        GetName = 1,
        GetRunspace = 0x37,
        GetVersion = 2,
        GetWindowPosition = 0x21,
        GetWindowSize = 0x27,
        GetWindowTitle = 0x29,
        NotifyBeginApplication = 9,
        NotifyEndApplication = 10,
        PopRunspace = 0x35,
        Prompt = 0x17,
        PromptForChoice = 0x1a,
        PromptForChoiceMultipleSelection = 0x38,
        PromptForCredential1 = 0x18,
        PromptForCredential2 = 0x19,
        PushRunspace = 0x34,
        ReadKey = 0x2e,
        ReadLine = 11,
        ReadLineAsSecureString = 12,
        ScrollBufferContents = 0x33,
        SetBackgroundColor = 30,
        SetBufferContents1 = 0x30,
        SetBufferContents2 = 0x31,
        SetBufferSize = 0x26,
        SetCursorPosition = 0x20,
        SetCursorSize = 0x24,
        SetForegroundColor = 0x1c,
        SetShouldExit = 6,
        SetWindowPosition = 0x22,
        SetWindowSize = 40,
        SetWindowTitle = 0x2a,
        Write1 = 13,
        Write2 = 14,
        WriteDebugLine = 0x13,
        WriteErrorLine = 0x12,
        WriteLine1 = 15,
        WriteLine2 = 0x10,
        WriteLine3 = 0x11,
        WriteProgress = 20,
        WriteVerboseLine = 0x15,
        WriteWarningLine = 0x16
    }
}

