//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.PowerShell.Commands.Management {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProcessResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProcessResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.PowerShell.Commands.Management.ProcessResources", typeof(ProcessResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command cannot be run completely because the system cannot find all the information required..
        /// </summary>
        public static string CannotStarttheProcess {
            get {
                return ResourceManager.GetString("CannotStarttheProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to perform the Stop-Process operation on the following item: {0}({1})?.
        /// </summary>
        public static string ConfirmStopProcess {
            get {
                return ResourceManager.GetString("ConfirmStopProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters &quot;{0}&quot; and &quot;{1}&quot; cannot be specified at the same time..
        /// </summary>
        public static string ContradictParametersSpecified {
            get {
                return ResourceManager.GetString("ContradictParametersSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot enumerate the file version information of the &quot;{0}&quot; process..
        /// </summary>
        public static string CouldnotEnumerateFileVer {
            get {
                return ResourceManager.GetString("CouldnotEnumerateFileVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot enumerate the modules and the file version information of the &quot;{0}&quot; process..
        /// </summary>
        public static string CouldnotEnumerateModuleFileVer {
            get {
                return ResourceManager.GetString("CouldnotEnumerateModuleFileVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot enumerate the modules of the &quot;{0}&quot; process..
        /// </summary>
        public static string CouldnotEnumerateModules {
            get {
                return ResourceManager.GetString("CouldnotEnumerateModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot stop process &quot;{0} ({1})&quot; because of the following error: {2}.
        /// </summary>
        public static string CouldNotStopProcess {
            get {
                return ResourceManager.GetString("CouldNotStopProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command cannot attach the debugger to the process due to {0} because no default debugger is available..
        /// </summary>
        public static string DebuggerError {
            get {
                return ResourceManager.GetString("DebuggerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command cannot be run because &quot;{0}&quot; and &quot;{1}&quot; are same. Give different inputs and Run your command again..
        /// </summary>
        public static string DuplicateEntry {
            get {
                return ResourceManager.GetString("DuplicateEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command cannot be run because the input &quot;{0}&quot; is not a valid Application.  Give a valid application and run your command again..
        /// </summary>
        public static string InvalidApplication {
            get {
                return ResourceManager.GetString("InvalidApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command cannot be run because either the parameter &quot;{0}&quot; has a value that is not valid or cannot be used with this command. Give a valid input and Run your command again..
        /// </summary>
        public static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command cannot be run due to the error: {0}..
        /// </summary>
        public static string InvalidStartProcess {
            get {
                return ResourceManager.GetString("InvalidStartProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command cannot be run due to error 1783. The possible cause of this error can be using of a non-existing user &quot;{0}&quot;. Please give a valid user and run your command again..
        /// </summary>
        public static string InvalidUserError {
            get {
                return ResourceManager.GetString("InvalidUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding &apos;{0}&apos; to the network: {1}.
        /// </summary>
        public static string JoinNetworkFailed {
            get {
                return ResourceManager.GetString("JoinNetworkFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception getting &quot;Modules&quot; or &quot;FileVersion&quot;: &quot;This feature is not supported for remote computers.&quot;..
        /// </summary>
        public static string NoComputerNameWithFileVersion {
            get {
                return ResourceManager.GetString("NoComputerNameWithFileVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command cannot be run because the debugger cannot be attached to the process &quot;{0} ({1})&quot;. Specify another process and Run your command..
        /// </summary>
        public static string NoDebuggerFound {
            get {
                return ResourceManager.GetString("NoDebuggerFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a process with the process identifier {1}..
        /// </summary>
        public static string NoProcessFoundForGivenId {
            get {
                return ResourceManager.GetString("NoProcessFoundForGivenId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a process with the name &quot;{0}&quot;. Verify the process name and call the cmdlet again..
        /// </summary>
        public static string NoProcessFoundForGivenName {
            get {
                return ResourceManager.GetString("NoProcessFoundForGivenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command stopped operation of &quot;{0} ({1})&quot; because of the following error: {2}..
        /// </summary>
        public static string Process_is_not_terminated {
            get {
                return ResourceManager.GetString("Process is not terminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        public static string ProcessNameForConfirmation {
            get {
                return ResourceManager.GetString("ProcessNameForConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command stopped operation because process &quot;{0} ({1})&quot; is not stopped in the specified time-out..
        /// </summary>
        public static string ProcessNotTerminated {
            get {
                return ResourceManager.GetString("ProcessNotTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command cannot be run because Redirection parameters cannot be used with UseShellExecute parameter.
        /// </summary>
        public static string RedirectionParams {
            get {
                return ResourceManager.GetString("RedirectionParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error removing &apos;{0}&apos; from the network: {1}.
        /// </summary>
        public static string RemoveFailed {
            get {
                return ResourceManager.GetString("RemoveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error renaming &apos;{0}&apos;: {1}.
        /// </summary>
        public static string RenameFailed {
            get {
                return ResourceManager.GetString("RenameFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified path is not a valid win32 application. Try again with the UseShellExecute..
        /// </summary>
        public static string UseShell {
            get {
                return ResourceManager.GetString("UseShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command stopped operation because it cannot wait on &apos;System Idle&apos; process. Specify another process and Run your command again..
        /// </summary>
        public static string WaitOnIdleProcess {
            get {
                return ResourceManager.GetString("WaitOnIdleProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command stopped operation because it cannot wait on itself. Specify another process and Run your command again..
        /// </summary>
        public static string WaitOnItself {
            get {
                return ResourceManager.GetString("WaitOnItself", resourceCulture);
            }
        }
    }
}
