namespace Microsoft.DnsClient.Commands
{
	public enum GetAdapterFlags
	{
		GAA_FLAG_DEFAULT = 0,
		GAA_FLAG_SKIP_UNICAST = 1,
		GAA_FLAG_SKIP_ANYCAST = 2,
		GAA_FLAG_SKIP_MULTICAST = 4,
		GAA_FLAG_SKIP_DNS_SERVER = 8,
		GAA_FLAG_INCLUDE_PREFIX = 16,
		GAA_FLAG_SKIP_FRIENDLY_NAME = 32,
		GAA_FLAG_INCLUDE_WINS_INFO = 64,
		GAA_FLAG_INCLUDE_GATEWAYS = 128,
		GAA_FLAG_INCLUDE_ALL_INTERFACES = 256,
		GAA_FLAG_INCLUDE_ALL_COMPARTMENTS = 512,
		GAA_FLAG_INCLUDE_TUNNEL_BINDINGORDER = 1024
	}
}